#define MY_SHIFT_KEYS \
  KS_GRV,  \ // `
  KS_TILD, \ // ~
  KS_1,    \ // 1
  KS_EXCL, \ // !
  KS_2,    \ // 2
  KS_AT,   \ // @
  KS_3,    \ // 3
  KS_HASH, \ // #
  KS_4,    \ // 4
  KS_DLR,  \ // $
  KS_5,    \ // 5
  KS_PERC, \ // %
  KS_6,    \ // 6
  KS_CIRC, \ // ^
  KS_7,    \ // 7
  KS_AMPR, \ // &
  KS_8,    \ // 8
  KS_ASTR, \ // *
  KS_9,    \ // 9
  KS_LPRN, \ // (
  KS_0,    \ // 0
  KS_RPRN, \ // )
  KS_HYPH, \ // -
  KS_UNDS, \ // _
  KS_EQL,  \ // =
  KS_PLUS, \ // +
  \
  KS_Q,    \ // q
  KS_S_Q,  \ // Q
  KS_W,    \ // w
  KS_S_W,  \ // W
  KS_E,    \ // e
  KS_S_E,  \ // E
  KS_R,    \ // r
  KS_S_R,  \ // R
  KS_T,    \ // t
  KS_S_T,  \ // T
  KS_Y,    \ // y
  KS_S_Y,  \ // Y
  KS_U,    \ // u
  KS_S_U,  \ // U
  KS_I,    \ // i
  KS_S_I,  \ // I
  KS_O,    \ // o
  KS_S_O,  \ // O
  KS_P,    \ // p
  KS_S_P,  \ // P
  KS_LBRC, \ // [
  KS_LCBR, \ // {
  KS_RBRC, \ // ]
  KS_RCBR, \ // }
  \
  KS_A,    \ // a
  KS_S_A,  \ // A
  KS_S,    \ // s
  KS_S_S,  \ // S
  KS_D,    \ // d
  KS_S_D,  \ // D
  KS_F,    \ // f
  KS_S_F,  \ // F
  KS_G,    \ // g
  KS_S_G,  \ // G
  KS_H,    \ // h
  KS_S_H,  \ // H
  KS_J,    \ // j
  KS_S_J,  \ // J
  KS_K,    \ // k
  KS_S_K,  \ // K
  KS_L,    \ // l
  KS_S_L,  \ // L
  KS_SCLN, \ // ;
  KS_COLN, \ // :
  KS_QUOT, \ // '
  KS_DQUO, \ // "
  KS_BSLS, \ /* \ */
  KS_PIPE, \ // |
  \
  KS_Z,    \ // z
  KS_S_Z,  \ // Z
  KS_X,    \ // x
  KS_S_X,  \ // X
  KS_C,    \ // c
  KS_S_C,  \ // C
  KS_V,    \ // v
  KS_S_V,  \ // V
  KS_B,    \ // b
  KS_S_B,  \ // B
  KS_N,    \ // n
  KS_S_N,  \ // N
  KS_M,    \ // m
  KS_S_M,  \ // M
  KS_COMM, \ // ,
  KS_LT,   \ // <
  KS_DOT,  \ // .
  KS_GT,   \ // >
  KS_SLSH, \ // /
  KS_QUES, \ // ?

Key shift_get_key(Key key) {
  switch (key) {
    case KS_GRV:  return KC_GRV;
    case KS_TILD: return KC_GRv;
    case KS_1:    return KC_1;
    case KS_EXCL: return KC_1;
    case KS_2:    return KC_2;
    case KS_AT:   return KC_2;
    case KS_3:    return KC_3;
    case KS_HASH: return KC_3;
    case KS_4:    return KC_4;
    case KS_DLR:  return KC_4;
    case KS_5:    return KC_5;
    case KS_PERC: return KC_5;
    case KS_6:    return KC_6;
    case KS_CIRC: return KC_6;
    case KS_7:    return KC_7;
    case KS_AMPR: return KC_7;
    case KS_8:    return KC_8;
    case KS_ASTR: return KC_8;
    case KS_9:    return KC_9;
    case KS_LPRN: return KC_9;
    case KS_0:    return KC_0;
    case KS_RPRN: return KC_0;
    case KS_HYPH: return KC_HYPH;
    case KS_UNDS: return KC_HYPH;
    case KS_EQL:  return KC_EQL;
    case KS_PLUS: return KC_EQL;
    case KS_Q:    return KC_Q;
    case KS_S_Q:  return KC_Q;
    case KS_W:    return KC_W;
    case KS_S_W:  return KC_W;
    case KS_E:    return KC_E;
    case KS_S_E:  return KC_E;
    case KS_R:    return KC_R;
    case KS_S_R:  return KC_R;
    case KS_T:    return KC_T;
    case KS_S_T:  return KC_T;
    case KS_Y:    return KC_Y;
    case KS_S_Y:  return KC_Y;
    case KS_U:    return KC_U;
    case KS_S_U:  return KC_U;
    case KS_I:    return KC_I;
    case KS_S_I:  return KC_I;
    case KS_O:    return KC_O;
    case KS_S_O:  return KC_O;
    case KS_P:    return KC_P;
    case KS_S_P:  return KC_P;
    case KS_LBRC: return KC_LBRC;
    case KS_LCBR: return KC_LBRC;
    case KS_RBRC: return KC_RBRC;
    case KS_RCBR: return KC_RBRC;
    case KS_A:    return KC_A;
    case KS_S_A:  return KC_A;
    case KS_S:    return KC_S;
    case KS_S_S:  return KC_S;
    case KS_D:    return KC_D;
    case KS_S_D:  return KC_D;
    case KS_F:    return KC_F;
    case KS_S_F:  return KC_F;
    case KS_G:    return KC_G;
    case KS_S_G:  return KC_G;
    case KS_H:    return KC_H;
    case KS_S_H:  return KC_H;
    case KS_J:    return KC_J;
    case KS_S_J:  return KC_J;
    case KS_K:    return KC_K;
    case KS_S_K:  return KC_K;
    case KS_L:    return KC_L;
    case KS_S_L:  return KC_L;
    case KS_SCLN: return KC_SCLN;
    case KS_COLN: return KC_SCLN;
    case KS_QUOT: return KC_QUOT;
    case KS_DQUO: return KC_QUOT;
    case KS_BSLS: return KC_BSLS;
    case KS_PIPE: return KC_BSLS;
    case KS_Z:    return KC_Z;
    case KS_S_Z:  return KC_Z;
    case KS_X:    return KC_X;
    case KS_S_X:  return KC_X;
    case KS_C:    return KC_C;
    case KS_S_C:  return KC_C;
    case KS_V:    return KC_V;
    case KS_S_V:  return KC_V;
    case KS_B:    return KC_B;
    case KS_S_B:  return KC_B;
    case KS_N:    return KC_N;
    case KS_S_N:  return KC_N;
    case KS_M:    return KC_M;
    case KS_S_M:  return KC_M;
    case KS_COMM: return KC_COMM;
    case KS_LT:   return KC_COMM;
    case KS_DOT:  return KC_DOT;
    case KS_GT:   return KC_DOT;
    case KS_SLSH: return KC_SLSH;
    case KS_QUES: return KC_SLSH;

    default: return -1;
  }
}

Shift shift_get_shift(Key key) {
  switch (key) {
    case EN_GRV:  return 0;
    case EN_TILD: return 1;
    case EN_1:    return 0;
    case EN_EXCL: return 1;
    case EN_2:    return 0;
    case EN_AT:   return 1;
    case EN_3:    return 0;
    case EN_HASH: return 1;
    case EN_4:    return 0;
    case EN_DLR:  return 1;
    case EN_5:    return 0;
    case EN_PERC: return 1;
    case EN_6:    return 0;
    case EN_CIRC: return 1;
    case EN_7:    return 0;
    case EN_AMPR: return 1;
    case EN_8:    return 0;
    case EN_ASTR: return 1;
    case EN_9:    return 0;
    case EN_LPRN: return 1;
    case EN_0:    return 0;
    case EN_RPRN: return 1;
    case EN_HYPH: return 0;
    case EN_UNDS: return 1;
    case EN_EQL:  return 0;
    case EN_PLUS: return 1;
    case EN_Q:    return 0;
    case EN_S_Q:  return 1;
    case EN_W:    return 0;
    case EN_S_W:  return 1;
    case EN_E:    return 0;
    case EN_S_E:  return 1;
    case EN_R:    return 0;
    case EN_S_R:  return 1;
    case EN_T:    return 0;
    case EN_S_T:  return 1;
    case EN_Y:    return 0;
    case EN_S_Y:  return 1;
    case EN_U:    return 0;
    case EN_S_U:  return 1;
    case EN_I:    return 0;
    case EN_S_I:  return 1;
    case EN_O:    return 0;
    case EN_S_O:  return 1;
    case EN_P:    return 0;
    case EN_S_P:  return 1;
    case EN_LBRC: return 0;
    case EN_LCBR: return 1;
    case EN_RBRC: return 0;
    case EN_RCBR: return 1;
    case EN_A:    return 0;
    case EN_S_A:  return 1;
    case EN_S:    return 0;
    case EN_S_S:  return 1;
    case EN_D:    return 0;
    case EN_S_D:  return 1;
    case EN_F:    return 0;
    case EN_S_F:  return 1;
    case EN_G:    return 0;
    case EN_S_G:  return 1;
    case EN_H:    return 0;
    case EN_S_H:  return 1;
    case EN_J:    return 0;
    case EN_S_J:  return 1;
    case EN_K:    return 0;
    case EN_S_K:  return 1;
    case EN_L:    return 0;
    case EN_S_L:  return 1;
    case EN_SCLN: return 0;
    case EN_COLN: return 1;
    case EN_QUOT: return 0;
    case EN_DQUO: return 1;
    case EN_BSLS: return 0;
    case EN_PIPE: return 1;
    case EN_Z:    return 0;
    case EN_S_Z:  return 1;
    case EN_X:    return 0;
    case EN_S_X:  return 1;
    case EN_C:    return 0;
    case EN_S_C:  return 1;
    case EN_V:    return 0;
    case EN_S_V:  return 1;
    case EN_B:    return 0;
    case EN_S_B:  return 1;
    case EN_N:    return 0;
    case EN_S_N:  return 1;
    case EN_M:    return 0;
    case EN_S_M:  return 1;
    case EN_COMM: return 0;
    case EN_LT:   return 1;
    case EN_DOT:  return 0;
    case EN_GT:   return 1;
    case EN_SLSH: return 0;
    case EN_QUES: return 1;

    default: return -1;
  }
}
