#define MY_LANG_KEYS \
  \ // Английские символы
  EN_GRV,  \ // `
  EN_TILD, \ // ~
  EN_1,    \ // 1
  EN_EXCL, \ // !
  EN_2,    \ // 2
  EN_AT,   \ // @
  EN_3,    \ // 3
  EN_HASH, \ // #
  EN_4,    \ // 4
  EN_DLR,  \ // $
  EN_5,    \ // 5
  EN_PERC, \ // %
  EN_6,    \ // 6
  EN_CIRC, \ // ^
  EN_7,    \ // 7
  EN_AMPR, \ // &
  EN_8,    \ // 8
  EN_ASTR, \ // *
  EN_9,    \ // 9
  EN_LPRN, \ // (
  EN_0,    \ // 0
  EN_RPRN, \ // )
  EN_HYPH, \ // -
  EN_UNDS, \ // _
  EN_EQL,  \ // =
  EN_PLUS, \ // +
  \
  EN_Q,    \ // q
  EN_S_Q,  \ // Q
  EN_W,    \ // w
  EN_S_W,  \ // W
  EN_E,    \ // e
  EN_S_E,  \ // E
  EN_R,    \ // r
  EN_S_R,  \ // R
  EN_T,    \ // t
  EN_S_T,  \ // T
  EN_Y,    \ // y
  EN_S_Y,  \ // Y
  EN_U,    \ // u
  EN_S_U,  \ // U
  EN_I,    \ // i
  EN_S_I,  \ // I
  EN_O,    \ // o
  EN_S_O,  \ // O
  EN_P,    \ // p
  EN_S_P,  \ // P
  EN_LBRC, \ // [
  EN_LCBR, \ // {
  EN_RBRC, \ // ]
  EN_RCBR, \ // }
  \
  EN_A,    \ // a
  EN_S_A,  \ // A
  EN_S,    \ // s
  EN_S_S,  \ // S
  EN_D,    \ // d
  EN_S_D,  \ // D
  EN_F,    \ // f
  EN_S_F,  \ // F
  EN_G,    \ // g
  EN_S_G,  \ // G
  EN_H,    \ // h
  EN_S_H,  \ // H
  EN_J,    \ // j
  EN_S_J,  \ // J
  EN_K,    \ // k
  EN_S_K,  \ // K
  EN_L,    \ // l
  EN_S_L,  \ // L
  EN_SCLN, \ // ;
  EN_COLN, \ // :
  EN_QUOT, \ // '
  EN_DQUO, \ // "
  EN_BSLS, \ /* \ */
  EN_PIPE, \ // |
  \
  EN_Z,    \ // z
  EN_S_Z,  \ // Z
  EN_X,    \ // x
  EN_S_X,  \ // X
  EN_C,    \ // c
  EN_S_C,  \ // C
  EN_V,    \ // v
  EN_S_V,  \ // V
  EN_B,    \ // b
  EN_S_B,  \ // B
  EN_N,    \ // n
  EN_S_N,  \ // N
  EN_M,    \ // m
  EN_S_M,  \ // M
  EN_COMM, \ // ,
  EN_LT,   \ // <
  EN_DOT,  \ // .
  EN_GT,   \ // >
  EN_SLSH, \ // /
  EN_QUES, \ // ?
  \, // -----------------------------------------------------------------------
  \, // Русские символы
  RU_JO,   \ // ё
  RU_S_JO, \ // Ё
  RU_1,    \ // 1
  RU_EXCL, \ // !
  RU_2,    \ // 2
  RU_DQUO, \ // "
  RU_3,    \ // 3
  RU_NUME, \ // №
  RU_4,    \ // 4
  RU_SCLN, \ // ;
  RU_5,    \ // 5
  RU_PERC, \ // %
  RU_6,    \ // 6
  RU_COLN, \ // :
  RU_7,    \ // 7
  RU_QUES, \ // ?
  RU_8,    \ // 8
  RU_ASTR, \ // *
  RU_9,    \ // 9
  RU_LPRN, \ // (
  RU_0,    \ // 0
  RU_RPRN, \ // )
  RU_HYPH, \ // -
  RU_UNDS, \ // _
  RU_EQL,  \ // =
  RU_PLUS, \ // +
  \
  RU_J,    \ // й
  RU_S_J,  \ // Й
  RU_TS,   \ // ц
  RU_S_TS, \ // Ц
  RU_U,    \ // у
  RU_S_U,  \ // У
  RU_K,    \ // к
  RU_S_K,  \ // К
  RU_JE,   \ // е
  RU_S_JE, \ // Е
  RU_N,    \ // н
  RU_S_N,  \ // Н
  RU_G,    \ // г
  RU_S_G,  \ // Г
  RU_SH,   \ // ш
  RU_S_SH, \ // Ш
  RU_SC,   \ // щ
  RU_S_SC, \ // Щ
  RU_Z,    \ // з
  RU_S_Z,  \ // З
  RU_H,    \ // х
  RU_S_H,  \ // Х
  RU_HD,   \ // ъ
  RU_S_HD, \ // Ъ
  \
  RU_F,    \ // ф
  RU_S_F,  \ // Ф
  RU_Y,    \ // ы
  RU_S_Y,  \ // Ы
  RU_V,    \ // в
  RU_S_V,  \ // В
  RU_A,    \ // а
  RU_S_A,  \ // А
  RU_P,    \ // п
  RU_S_P,  \ // п
  RU_R,    \ // р
  RU_S_R,  \ // Р
  RU_O,    \ // о
  RU_S_O,  \ // О
  RU_L,    \ // л
  RU_S_L,  \ // Л
  RU_D,    \ // д
  RU_S_D,  \ // Д
  RU_ZH,   \ // ж
  RU_S_ZH, \ // Ж
  RU_E,    \ // э
  RU_S_E,  \ // Э
  RU_BSLS, \ /* \ */
  RU_SLSH, \ // /
  \
  RU_JA,   \ // я
  RU_S_JA, \ // Я
  RU_CH,   \ // ч
  RU_S_CH, \ // Ч
  RU_S,    \ // с
  RU_S_S,  \ // С
  RU_M,    \ // м
  RU_S_M,  \ // М
  RU_I,    \ // и
  RU_S_I,  \ // И
  RU_T,    \ // т
  RU_S_T,  \ // Т
  RU_SF,   \ // ь
  RU_S_SF, \ // Ь
  RU_B,    \ // б
  RU_S_B,  \ // Б
  RU_JU,   \ // ю
  RU_S_JU, \ // Ю
  RU_DOT,  \ // .
  RU_COMM, \ // ,

Key lang_get_key(Key key) {
  switch (key) {
    case EN_GRV:  return KS_GRV;
    case EN_TILD: return KS_TILD;
    case EN_1:    return KS_1;
    case EN_EXCL: return KS_EXCL;
    case EN_2:    return KS_2;
    case EN_AT:   return KS_AT;
    case EN_3:    return KS_3;
    case EN_HASH: return KS_HASH;
    case EN_4:    return KS_4;
    case EN_DLR:  return KS_DLR;
    case EN_5:    return KS_5;
    case EN_PERC: return KS_PERC;
    case EN_6:    return KS_6;
    case EN_CIRC: return KS_CIRC;
    case EN_7:    return KS_7;
    case EN_AMPR: return KS_AMPR;
    case EN_8:    return KS_8;
    case EN_ASTR: return KS_ASTR;
    case EN_9:    return KS_9;
    case EN_LPRN: return KS_LPRN;
    case EN_0:    return KS_0;
    case EN_RPRN: return KS_RPRN;
    case EN_HYPH: return KS_HYPH;
    case EN_UNDS: return KS_UNDS;
    case EN_EQL:  return KS_EQL;
    case EN_PLUS: return KS_PLUS;
    case EN_Q:    return KS_Q;
    case EN_S_Q:  return KS_S_Q;
    case EN_W:    return KS_W;
    case EN_S_W:  return KS_S_W;
    case EN_E:    return KS_E;
    case EN_S_E:  return KS_S_E;
    case EN_R:    return KS_R;
    case EN_S_R:  return KS_S_R;
    case EN_T:    return KS_T;
    case EN_S_T:  return KS_S_T;
    case EN_Y:    return KS_Y;
    case EN_S_Y:  return KS_S_Y;
    case EN_U:    return KS_U;
    case EN_S_U:  return KS_S_U;
    case EN_I:    return KS_I;
    case EN_S_I:  return KS_S_I;
    case EN_O:    return KS_O;
    case EN_S_O:  return KS_S_O;
    case EN_P:    return KS_P;
    case EN_S_P:  return KS_S_P;
    case EN_LBRC: return KS_LBRC;
    case EN_LCBR: return KS_LCBR;
    case EN_RBRC: return KS_RBRC;
    case EN_RCBR: return KS_RCBR;
    case EN_A:    return KS_A;
    case EN_S_A:  return KS_S_A;
    case EN_S:    return KS_S;
    case EN_S_S:  return KS_S_S;
    case EN_D:    return KS_D;
    case EN_S_D:  return KS_S_D;
    case EN_F:    return KS_F;
    case EN_S_F:  return KS_S_F;
    case EN_G:    return KS_G;
    case EN_S_G:  return KS_S_G;
    case EN_H:    return KS_H;
    case EN_S_H:  return KS_S_H;
    case EN_J:    return KS_J;
    case EN_S_J:  return KS_S_J;
    case EN_K:    return KS_K;
    case EN_S_K:  return KS_S_K;
    case EN_L:    return KS_L;
    case EN_S_L:  return KS_S_L;
    case EN_SCLN: return KS_SCLN;
    case EN_COLN: return KS_COLN;
    case EN_QUOT: return KS_QUOT;
    case EN_DQUO: return KS_DQUO;
    case EN_BSLS: return KS_BSLS;
    case EN_PIPE: return KS_PIPE;
    case EN_Z:    return KS_Z;
    case EN_S_Z:  return KS_S_Z;
    case EN_X:    return KS_X;
    case EN_S_X:  return KS_S_X;
    case EN_C:    return KS_C;
    case EN_S_C:  return KS_S_C;
    case EN_V:    return KS_V;
    case EN_S_V:  return KS_S_V;
    case EN_B:    return KS_B;
    case EN_S_B:  return KS_S_B;
    case EN_N:    return KS_N;
    case EN_S_N:  return KS_S_N;
    case EN_M:    return KS_M;
    case EN_S_M:  return KS_S_M;
    case EN_COMM: return KS_COMM;
    case EN_LT:   return KS_LT;
    case EN_DOT:  return KS_DOT;
    case EN_GT:   return KS_GT;
    case EN_SLSH: return KS_SLSH;
    case EN_QUES: return KS_QUES;

    case RU_JO:   return KS_GRV;
    case RU_S_JO: return KS_TILD;
    case RU_1:    return KS_1;
    case RU_EXCL: return KS_EXCL;
    case RU_2:    return KS_2;
    case RU_DQUO: return KS_AT;
    case RU_3:    return KS_3;
    case RU_NUME: return KS_HASH;
    case RU_4:    return KS_4;
    case RU_SCLN: return KS_DLR;
    case RU_5:    return KS_5;
    case RU_PERC: return KS_PERC;
    case RU_6:    return KS_6;
    case RU_COLN: return KS_CIRC;
    case RU_7:    return KS_7;
    case RU_QUES: return KS_AMPR;
    case RU_8:    return KS_8;
    case RU_ASTR: return KS_ASTR;
    case RU_9:    return KS_9;
    case RU_LPRN: return KS_LPRN;
    case RU_0:    return KS_0;
    case RU_RPRN: return KS_RPRN;
    case RU_HYPH: return KS_HYPH;
    case RU_UNDS: return KS_UNDS;
    case RU_EQL:  return KS_EQL;
    case RU_PLUS: return KS_PLUS;
    case RU_J:    return KS_Q;
    case RU_S_J:  return KS_S_Q;
    case RU_TS:   return KS_W;
    case RU_S_TS: return KS_S_W;
    case RU_U:    return KS_E;
    case RU_S_U:  return KS_S_E;
    case RU_K:    return KS_R;
    case RU_S_K:  return KS_S_R;
    case RU_JE:   return KS_T;
    case RU_S_JE: return KS_S_T;
    case RU_N:    return KS_Y;
    case RU_S_N:  return KS_S_Y;
    case RU_G:    return KS_U;
    case RU_S_G:  return KS_S_U;
    case RU_SH:   return KS_I;
    case RU_S_SH: return KS_S_I;
    case RU_SC:   return KS_O;
    case RU_S_SC: return KS_S_O;
    case RU_Z:    return KS_P;
    case RU_S_Z:  return KS_S_P;
    case RU_H:    return KS_LBRC;
    case RU_S_H:  return KS_LCBR;
    case RU_HD:   return KS_RBRC;
    case RU_S_HD: return KS_RCBR;
    case RU_F:    return KS_A;
    case RU_S_F:  return KS_S_A;
    case RU_Y:    return KS_S;
    case RU_S_Y:  return KS_S_S;
    case RU_V:    return KS_D;
    case RU_S_V:  return KS_S_D;
    case RU_A:    return KS_F;
    case RU_S_A:  return KS_S_F;
    case RU_P:    return KS_G;
    case RU_S_P:  return KS_S_G;
    case RU_R:    return KS_H;
    case RU_S_R:  return KS_S_H;
    case RU_O:    return KS_J;
    case RU_S_O:  return KS_S_J;
    case RU_L:    return KS_K;
    case RU_S_L:  return KS_S_K;
    case RU_D:    return KS_L;
    case RU_S_D:  return KS_S_L;
    case RU_ZH:   return KS_SCLN;
    case RU_S_ZH: return KS_COLN;
    case RU_E:    return KS_QUOT;
    case RU_S_E:  return KS_DQUO;
    case RU_BSLS: return KS_BSLS;
    case RU_SLSH: return KS_PIPE;
    case RU_JA:   return KS_Z;
    case RU_S_JA: return KS_S_Z;
    case RU_CH:   return KS_X;
    case RU_S_CH: return KS_S_X;
    case RU_S:    return KS_C;
    case RU_S_S:  return KS_S_C;
    case RU_M:    return KS_V;
    case RU_S_M:  return KS_S_V;
    case RU_I:    return KS_B;
    case RU_S_I:  return KS_S_B;
    case RU_T:    return KS_N;
    case RU_S_T:  return KS_S_N;
    case RU_SF:   return KS_M;
    case RU_S_SF: return KS_S_M;
    case RU_B:    return KS_COMM;
    case RU_S_B:  return KS_LT;
    case RU_JU:   return KS_DOT;
    case RU_S_JU: return KS_GT;
    case RU_DOT:  return KS_SLSH;
    case RU_COMM: return KS_QUES;
    
    default: return -1;
  }
}

Lang lang_get_lang(Key key) {
  switch (key) {
    case EN_GRV:  return 0;
    case EN_TILD: return 0;
    case EN_1:    return 0;
    case EN_EXCL: return 0;
    case EN_2:    return 0;
    case EN_AT:   return 0;
    case EN_3:    return 0;
    case EN_HASH: return 0;
    case EN_4:    return 0;
    case EN_DLR:  return 0;
    case EN_5:    return 0;
    case EN_PERC: return 0;
    case EN_6:    return 0;
    case EN_CIRC: return 0;
    case EN_7:    return 0;
    case EN_AMPR: return 0;
    case EN_8:    return 0;
    case EN_ASTR: return 0;
    case EN_9:    return 0;
    case EN_LPRN: return 0;
    case EN_0:    return 0;
    case EN_RPRN: return 0;
    case EN_HYPH: return 0;
    case EN_UNDS: return 0;
    case EN_EQL:  return 0;
    case EN_PLUS: return 0;
    case EN_Q:    return 0;
    case EN_S_Q:  return 0;
    case EN_W:    return 0;
    case EN_S_W:  return 0;
    case EN_E:    return 0;
    case EN_S_E:  return 0;
    case EN_R:    return 0;
    case EN_S_R:  return 0;
    case EN_T:    return 0;
    case EN_S_T:  return 0;
    case EN_Y:    return 0;
    case EN_S_Y:  return 0;
    case EN_U:    return 0;
    case EN_S_U:  return 0;
    case EN_I:    return 0;
    case EN_S_I:  return 0;
    case EN_O:    return 0;
    case EN_S_O:  return 0;
    case EN_P:    return 0;
    case EN_S_P:  return 0;
    case EN_LBRC: return 0;
    case EN_LCBR: return 0;
    case EN_RBRC: return 0;
    case EN_RCBR: return 0;
    case EN_A:    return 0;
    case EN_S_A:  return 0;
    case EN_S:    return 0;
    case EN_S_S:  return 0;
    case EN_D:    return 0;
    case EN_S_D:  return 0;
    case EN_F:    return 0;
    case EN_S_F:  return 0;
    case EN_G:    return 0;
    case EN_S_G:  return 0;
    case EN_H:    return 0;
    case EN_S_H:  return 0;
    case EN_J:    return 0;
    case EN_S_J:  return 0;
    case EN_K:    return 0;
    case EN_S_K:  return 0;
    case EN_L:    return 0;
    case EN_S_L:  return 0;
    case EN_SCLN: return 0;
    case EN_COLN: return 0;
    case EN_QUOT: return 0;
    case EN_DQUO: return 0;
    case EN_BSLS: return 0;
    case EN_PIPE: return 0;
    case EN_Z:    return 0;
    case EN_S_Z:  return 0;
    case EN_X:    return 0;
    case EN_S_X:  return 0;
    case EN_C:    return 0;
    case EN_S_C:  return 0;
    case EN_V:    return 0;
    case EN_S_V:  return 0;
    case EN_B:    return 0;
    case EN_S_B:  return 0;
    case EN_N:    return 0;
    case EN_S_N:  return 0;
    case EN_M:    return 0;
    case EN_S_M:  return 0;
    case EN_COMM: return 0;
    case EN_LT:   return 0;
    case EN_DOT:  return 0;
    case EN_GT:   return 0;
    case EN_SLSH: return 0;
    case EN_QUES: return 0;

    case RU_JO:   return 1;
    case RU_S_JO: return 1;
    case RU_1:    return 1;
    case RU_EXCL: return 1;
    case RU_2:    return 1;
    case RU_DQUO: return 1;
    case RU_3:    return 1;
    case RU_NUME: return 1;
    case RU_4:    return 1;
    case RU_SCLN: return 1;
    case RU_5:    return 1;
    case RU_PERC: return 1;
    case RU_6:    return 1;
    case RU_COLN: return 1;
    case RU_7:    return 1;
    case RU_QUES: return 1;
    case RU_8:    return 1;
    case RU_ASTR: return 1;
    case RU_9:    return 1;
    case RU_LPRN: return 1;
    case RU_0:    return 1;
    case RU_RPRN: return 1;
    case RU_HYPH: return 1;
    case RU_UNDS: return 1;
    case RU_EQL:  return 1;
    case RU_PLUS: return 1;
    case RU_J:    return 1;
    case RU_S_J:  return 1;
    case RU_TS:   return 1;
    case RU_S_TS: return 1;
    case RU_U:    return 1;
    case RU_S_U:  return 1;
    case RU_K:    return 1;
    case RU_S_K:  return 1;
    case RU_JE:   return 1;
    case RU_S_JE: return 1;
    case RU_N:    return 1;
    case RU_S_N:  return 1;
    case RU_G:    return 1;
    case RU_S_G:  return 1;
    case RU_SH:   return 1;
    case RU_S_SH: return 1;
    case RU_SC:   return 1;
    case RU_S_SC: return 1;
    case RU_Z:    return 1;
    case RU_S_Z:  return 1;
    case RU_H:    return 1;
    case RU_S_H:  return 1;
    case RU_HD:   return 1;
    case RU_S_HD: return 1;
    case RU_F:    return 1;
    case RU_S_F:  return 1;
    case RU_Y:    return 1;
    case RU_S_Y:  return 1;
    case RU_V:    return 1;
    case RU_S_V:  return 1;
    case RU_A:    return 1;
    case RU_S_A:  return 1;
    case RU_P:    return 1;
    case RU_S_P:  return 1;
    case RU_R:    return 1;
    case RU_S_R:  return 1;
    case RU_O:    return 1;
    case RU_S_O:  return 1;
    case RU_L:    return 1;
    case RU_S_L:  return 1;
    case RU_D:    return 1;
    case RU_S_D:  return 1;
    case RU_ZH:   return 1;
    case RU_S_ZH: return 1;
    case RU_E:    return 1;
    case RU_S_E:  return 1;
    case RU_BSLS: return 1;
    case RU_SLSH: return 1;
    case RU_JA:   return 1;
    case RU_S_JA: return 1;
    case RU_CH:   return 1;
    case RU_S_CH: return 1;
    case RU_S:    return 1;
    case RU_S_S:  return 1;
    case RU_M:    return 1;
    case RU_S_M:  return 1;
    case RU_I:    return 1;
    case RU_S_I:  return 1;
    case RU_T:    return 1;
    case RU_S_T:  return 1;
    case RU_SF:   return 1;
    case RU_S_SF: return 1;
    case RU_B:    return 1;
    case RU_S_B:  return 1;
    case RU_JU:   return 1;
    case RU_S_JU: return 1;
    case RU_DOT:  return 1;
    case RU_COMM: return 1;

    default: return -1;
  }
}
